//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.01 at 08:52:49 PM CEST 
//


package org.opencds.vmr.v1_0.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * The situation or context within which a CDS evaluation is made.  Included in CDS inputs for HL7 Context-Aware Knowledge Retrieval (Infobutton) Knowledge Request standard.  Used, for example, to generate human-readable care guidance in the end-user's preferred language.
 * 
 * <p>Java class for CDSContext complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CDSContext">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdsSystemUserType" type="{org.opencds.vmr.v1_0.schema.datatypes}CD" minOccurs="0"/>
 *         &lt;element name="cdsSystemUserPreferredLanguage" type="{org.opencds.vmr.v1_0.schema.datatypes}CD" minOccurs="0"/>
 *         &lt;element name="cdsInformationRecipientType" type="{org.opencds.vmr.v1_0.schema.datatypes}CD" minOccurs="0"/>
 *         &lt;element name="cdsInformationRecipientPreferredLanguage" type="{org.opencds.vmr.v1_0.schema.datatypes}CD" minOccurs="0"/>
 *         &lt;element name="cdsSystemUserTaskContext" type="{org.opencds.vmr.v1_0.schema.datatypes}CD" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CDSContext", namespace = "org.opencds.vmr.v1_0.schema.cdsinput", propOrder = {
    "cdsSystemUserType",
    "cdsSystemUserPreferredLanguage",
    "cdsInformationRecipientType",
    "cdsInformationRecipientPreferredLanguage",
    "cdsSystemUserTaskContext"
})
public class CDSContext {

    protected CD cdsSystemUserType;
    protected CD cdsSystemUserPreferredLanguage;
    protected CD cdsInformationRecipientType;
    protected CD cdsInformationRecipientPreferredLanguage;
    protected CD cdsSystemUserTaskContext;

    /**
     * Gets the value of the cdsSystemUserType property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getCdsSystemUserType() {
        return cdsSystemUserType;
    }

    /**
     * Sets the value of the cdsSystemUserType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setCdsSystemUserType(CD value) {
        this.cdsSystemUserType = value;
    }

    /**
     * Gets the value of the cdsSystemUserPreferredLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getCdsSystemUserPreferredLanguage() {
        return cdsSystemUserPreferredLanguage;
    }

    /**
     * Sets the value of the cdsSystemUserPreferredLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setCdsSystemUserPreferredLanguage(CD value) {
        this.cdsSystemUserPreferredLanguage = value;
    }

    /**
     * Gets the value of the cdsInformationRecipientType property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getCdsInformationRecipientType() {
        return cdsInformationRecipientType;
    }

    /**
     * Sets the value of the cdsInformationRecipientType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setCdsInformationRecipientType(CD value) {
        this.cdsInformationRecipientType = value;
    }

    /**
     * Gets the value of the cdsInformationRecipientPreferredLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getCdsInformationRecipientPreferredLanguage() {
        return cdsInformationRecipientPreferredLanguage;
    }

    /**
     * Sets the value of the cdsInformationRecipientPreferredLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setCdsInformationRecipientPreferredLanguage(CD value) {
        this.cdsInformationRecipientPreferredLanguage = value;
    }

    /**
     * Gets the value of the cdsSystemUserTaskContext property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getCdsSystemUserTaskContext() {
        return cdsSystemUserTaskContext;
    }

    /**
     * Sets the value of the cdsSystemUserTaskContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setCdsSystemUserTaskContext(CD value) {
        this.cdsSystemUserTaskContext = value;
    }

}
