//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.01 at 12:54:04 AM CEST 
//


package org.opencds.vmr.v1_0.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Referred to in CDA release 2 as maxDoseQuantity.  Specifies the maximum dose that can be given in a specified time interval.
 * 
 * <p>Java class for DoseRestriction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DoseRestriction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="maxDoseForInterval" type="{org.opencds.vmr.v1_0.schema.datatypes}PQ"/>
 *         &lt;element name="timeInterval" type="{org.opencds.vmr.v1_0.schema.datatypes}PQ"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DoseRestriction", propOrder = {
    "maxDoseForInterval",
    "timeInterval"
})
public class DoseRestriction {

    @XmlElement(required = true)
    protected PQ maxDoseForInterval;
    @XmlElement(required = true)
    protected PQ timeInterval;

    /**
     * Gets the value of the maxDoseForInterval property.
     * 
     * @return
     *     possible object is
     *     {@link PQ }
     *     
     */
    public PQ getMaxDoseForInterval() {
        return maxDoseForInterval;
    }

    /**
     * Sets the value of the maxDoseForInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link PQ }
     *     
     */
    public void setMaxDoseForInterval(PQ value) {
        this.maxDoseForInterval = value;
    }

    /**
     * Gets the value of the timeInterval property.
     * 
     * @return
     *     possible object is
     *     {@link PQ }
     *     
     */
    public PQ getTimeInterval() {
        return timeInterval;
    }

    /**
     * Sets the value of the timeInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link PQ }
     *     
     */
    public void setTimeInterval(PQ value) {
        this.timeInterval = value;
    }

}
