//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.01 at 06:23:30 PM CEST 
//


package org.opencds.vmr.v1_0.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The relationship between one Entity and another Entity, in a list structure.
 * 
 * <p>Java class for EntityRelationship complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EntityRelationship">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sourceId" type="{org.opencds.vmr.v1_0.schema.datatypes}II"/>
 *         &lt;element name="targetEntityId" type="{org.opencds.vmr.v1_0.schema.datatypes}II"/>
 *         &lt;element name="targetRole" type="{org.opencds.vmr.v1_0.schema.datatypes}CD"/>
 *         &lt;element name="relationshipTimeInterval" type="{org.opencds.vmr.v1_0.schema.datatypes}IVL_TS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntityRelationship", propOrder = {
    "sourceId",
    "targetEntityId",
    "targetRole",
    "relationshipTimeInterval"
})
public class EntityRelationship {

    @XmlElement(required = true)
    protected II sourceId;
    @XmlElement(required = true)
    protected II targetEntityId;
    @XmlElement(required = true)
    protected CD targetRole;
    protected IVLTS relationshipTimeInterval;

    /**
     * Gets the value of the sourceId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getSourceId() {
        return sourceId;
    }

    /**
     * Sets the value of the sourceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setSourceId(II value) {
        this.sourceId = value;
    }

    /**
     * Gets the value of the targetEntityId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getTargetEntityId() {
        return targetEntityId;
    }

    /**
     * Sets the value of the targetEntityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setTargetEntityId(II value) {
        this.targetEntityId = value;
    }

    /**
     * Gets the value of the targetRole property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getTargetRole() {
        return targetRole;
    }

    /**
     * Sets the value of the targetRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setTargetRole(CD value) {
        this.targetRole = value;
    }

    /**
     * Gets the value of the relationshipTimeInterval property.
     * 
     * @return
     *     possible object is
     *     {@link IVLTS }
     *     
     */
    public IVLTS getRelationshipTimeInterval() {
        return relationshipTimeInterval;
    }

    /**
     * Sets the value of the relationshipTimeInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLTS }
     *     
     */
    public void setRelationshipTimeInterval(IVLTS value) {
        this.relationshipTimeInterval = value;
    }

}
