//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.01 at 06:23:30 PM CEST 
//


package org.opencds.vmr.v1_0.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * A set of consecutive values of an ordered base datatype. 
 * 
 * Any ordered type can be the basis of an IVL; it does not matter whether the base type is discrete or continuous. If the base datatype is only partially ordered, all elements of the IVL must be elements of a totally ordered subset of the partially ordered datatype. For example, PQ is considered ordered. However the ordering of PQs is only partial; a total order is only defined among comparable quantities (quantities of the same physical dimension). While IVLs between 2 and 4 meter exists, there is no IVL between 2 meters and 4 seconds.
 * 
 * <p>Java class for IVL_PQ complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IVL_PQ">
 *   &lt;complexContent>
 *     &lt;extension base="{org.opencds.vmr.v1_0.schema.datatypes}ANY">
 *       &lt;attGroup ref="{org.opencds.vmr.v1_0.schema.datatypes}ATTR_PQ_HIGH"/>
 *       &lt;attGroup ref="{org.opencds.vmr.v1_0.schema.datatypes}ATTR_PQ_LOW"/>
 *       &lt;attribute name="lowIsInclusive" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="highIsInclusive" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IVL_PQ", namespace = "org.opencds.vmr.v1_0.schema.datatypes")
public class IVLPQ
    extends ANY
{

    @XmlAttribute(name = "lowIsInclusive")
    protected Boolean lowIsInclusive;
    @XmlAttribute(name = "highIsInclusive")
    protected Boolean highIsInclusive;
    @XmlAttribute(name = "highValue", required = true)
    protected double highValue;
    @XmlAttribute(name = "highUnit", required = true)
    protected String highUnit;
    @XmlAttribute(name = "lowValue", required = true)
    protected double lowValue;
    @XmlAttribute(name = "lowUnit", required = true)
    protected String lowUnit;

    /**
     * Gets the value of the lowIsInclusive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLowIsInclusive() {
        return lowIsInclusive;
    }

    /**
     * Sets the value of the lowIsInclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLowIsInclusive(Boolean value) {
        this.lowIsInclusive = value;
    }

    /**
     * Gets the value of the highIsInclusive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHighIsInclusive() {
        return highIsInclusive;
    }

    /**
     * Sets the value of the highIsInclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHighIsInclusive(Boolean value) {
        this.highIsInclusive = value;
    }

    /**
     * Gets the value of the highValue property.
     * 
     */
    public double getHighValue() {
        return highValue;
    }

    /**
     * Sets the value of the highValue property.
     * 
     */
    public void setHighValue(double value) {
        this.highValue = value;
    }

    /**
     * Gets the value of the highUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHighUnit() {
        return highUnit;
    }

    /**
     * Sets the value of the highUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHighUnit(String value) {
        this.highUnit = value;
    }

    /**
     * Gets the value of the lowValue property.
     * 
     */
    public double getLowValue() {
        return lowValue;
    }

    /**
     * Sets the value of the lowValue property.
     * 
     */
    public void setLowValue(double value) {
        this.lowValue = value;
    }

    /**
     * Gets the value of the lowUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLowUnit() {
        return lowUnit;
    }

    /**
     * Sets the value of the lowUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLowUnit(String value) {
        this.lowUnit = value;
    }

}
