//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.01 at 12:54:04 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "org.opencds.vmr.v1_0.schema.vmr")
package org.opencds.vmr.v1_0.schema;
