//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.01 at 06:23:30 PM CEST 
//


package org.opencds.vmr.v1_0.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies the data required regarding entities related to the evaluated person of interest.
 * 
 * <p>Java class for RelatedEntityInputSpecification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelatedEntityInputSpecification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requiredRelationshipType" type="{org.opencds.vmr.v1_0.schema.datatypes}CD"/>
 *         &lt;element name="requiredEntityTemplate" type="{org.opencds.vmr.v1_0.schema.datatypes}II" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="requiredRelationshipSearchBackTimePeriod" type="{org.opencds.vmr.v1_0.schema.datatypes}PQ" minOccurs="0"/>
 *         &lt;element name="requiredRelationshipSearchFowardTimePeriod" type="{org.opencds.vmr.v1_0.schema.datatypes}PQ" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelatedEntityInputSpecification", namespace = "org.opencds.vmr.v1_0.schema.cdsinput.specification", propOrder = {
    "requiredRelationshipType",
    "requiredEntityTemplate",
    "requiredRelationshipSearchBackTimePeriod",
    "requiredRelationshipSearchFowardTimePeriod"
})
public class RelatedEntityInputSpecification {

    @XmlElement(required = true)
    protected CD requiredRelationshipType;
    protected List<II> requiredEntityTemplate;
    protected PQ requiredRelationshipSearchBackTimePeriod;
    protected PQ requiredRelationshipSearchFowardTimePeriod;

    /**
     * Gets the value of the requiredRelationshipType property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getRequiredRelationshipType() {
        return requiredRelationshipType;
    }

    /**
     * Sets the value of the requiredRelationshipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setRequiredRelationshipType(CD value) {
        this.requiredRelationshipType = value;
    }

    /**
     * Gets the value of the requiredEntityTemplate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requiredEntityTemplate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequiredEntityTemplate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getRequiredEntityTemplate() {
        if (requiredEntityTemplate == null) {
            requiredEntityTemplate = new ArrayList<II>();
        }
        return this.requiredEntityTemplate;
    }

    /**
     * Gets the value of the requiredRelationshipSearchBackTimePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link PQ }
     *     
     */
    public PQ getRequiredRelationshipSearchBackTimePeriod() {
        return requiredRelationshipSearchBackTimePeriod;
    }

    /**
     * Sets the value of the requiredRelationshipSearchBackTimePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PQ }
     *     
     */
    public void setRequiredRelationshipSearchBackTimePeriod(PQ value) {
        this.requiredRelationshipSearchBackTimePeriod = value;
    }

    /**
     * Gets the value of the requiredRelationshipSearchFowardTimePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link PQ }
     *     
     */
    public PQ getRequiredRelationshipSearchFowardTimePeriod() {
        return requiredRelationshipSearchFowardTimePeriod;
    }

    /**
     * Sets the value of the requiredRelationshipSearchFowardTimePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PQ }
     *     
     */
    public void setRequiredRelationshipSearchFowardTimePeriod(PQ value) {
        this.requiredRelationshipSearchFowardTimePeriod = value;
    }

}
