//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.01 at 08:48:19 PM CEST 
//


package org.opencds.vmr.v1_0.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Abstract base class for giving a material of a particular constitution to a person to enable a clinical effect.
 * 
 * <p>Java class for SubstanceAdministrationBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubstanceAdministrationBase">
 *   &lt;complexContent>
 *     &lt;extension base="{org.opencds.vmr.v1_0.schema.vmr}ClinicalStatement">
 *       &lt;sequence>
 *         &lt;element name="substanceAdministrationGeneralPurpose" type="{org.opencds.vmr.v1_0.schema.datatypes}CD" minOccurs="0"/>
 *         &lt;element name="doseType" type="{org.opencds.vmr.v1_0.schema.datatypes}CD" minOccurs="0"/>
 *         &lt;element name="substance" type="{org.opencds.vmr.v1_0.schema.vmr}AdministrableSubstance"/>
 *         &lt;element name="doseQuantity" type="{org.opencds.vmr.v1_0.schema.datatypes}IVL_PQ" minOccurs="0"/>
 *         &lt;element name="deliveryRoute" type="{org.opencds.vmr.v1_0.schema.datatypes}CD" minOccurs="0"/>
 *         &lt;element name="deliveryRate" type="{org.opencds.vmr.v1_0.schema.datatypes}IVL_PQ" minOccurs="0"/>
 *         &lt;element name="dosingPeriod" type="{org.opencds.vmr.v1_0.schema.datatypes}IVL_PQ" minOccurs="0"/>
 *         &lt;element name="dosingPeriodIntervalIsImportant" type="{org.opencds.vmr.v1_0.schema.datatypes}BL" minOccurs="0"/>
 *         &lt;element name="deliveryMethod" type="{org.opencds.vmr.v1_0.schema.datatypes}CD" minOccurs="0"/>
 *         &lt;element name="approachBodySite" type="{org.opencds.vmr.v1_0.schema.vmr}BodySite" minOccurs="0"/>
 *         &lt;element name="targetBodySite" type="{org.opencds.vmr.v1_0.schema.vmr}BodySite" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubstanceAdministrationBase", propOrder = {
    "substanceAdministrationGeneralPurpose",
    "doseType",
    "substance",
    "doseQuantity",
    "deliveryRoute",
    "deliveryRate",
    "dosingPeriod",
    "dosingPeriodIntervalIsImportant",
    "deliveryMethod",
    "approachBodySite",
    "targetBodySite"
})
@XmlSeeAlso({
    SubstanceAdministrationOrder.class,
    SubstanceDispensationEvent.class,
    SubstanceAdministrationEvent.class,
    SubstanceAdministrationProposal.class,
    UndeliveredSubstanceAdministration.class
})
public abstract class SubstanceAdministrationBase
    extends ClinicalStatement
{

    protected CD substanceAdministrationGeneralPurpose;
    protected CD doseType;
    @XmlElement(required = true)
    protected AdministrableSubstance substance;
    protected IVLPQ doseQuantity;
    protected CD deliveryRoute;
    protected IVLPQ deliveryRate;
    protected IVLPQ dosingPeriod;
    protected BL dosingPeriodIntervalIsImportant;
    protected CD deliveryMethod;
    protected BodySite approachBodySite;
    protected BodySite targetBodySite;

    /**
     * Gets the value of the substanceAdministrationGeneralPurpose property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getSubstanceAdministrationGeneralPurpose() {
        return substanceAdministrationGeneralPurpose;
    }

    /**
     * Sets the value of the substanceAdministrationGeneralPurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setSubstanceAdministrationGeneralPurpose(CD value) {
        this.substanceAdministrationGeneralPurpose = value;
    }

    /**
     * Gets the value of the doseType property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getDoseType() {
        return doseType;
    }

    /**
     * Sets the value of the doseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setDoseType(CD value) {
        this.doseType = value;
    }

    /**
     * Gets the value of the substance property.
     * 
     * @return
     *     possible object is
     *     {@link AdministrableSubstance }
     *     
     */
    public AdministrableSubstance getSubstance() {
        return substance;
    }

    /**
     * Sets the value of the substance property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdministrableSubstance }
     *     
     */
    public void setSubstance(AdministrableSubstance value) {
        this.substance = value;
    }

    /**
     * Gets the value of the doseQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link IVLPQ }
     *     
     */
    public IVLPQ getDoseQuantity() {
        return doseQuantity;
    }

    /**
     * Sets the value of the doseQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLPQ }
     *     
     */
    public void setDoseQuantity(IVLPQ value) {
        this.doseQuantity = value;
    }

    /**
     * Gets the value of the deliveryRoute property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getDeliveryRoute() {
        return deliveryRoute;
    }

    /**
     * Sets the value of the deliveryRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setDeliveryRoute(CD value) {
        this.deliveryRoute = value;
    }

    /**
     * Gets the value of the deliveryRate property.
     * 
     * @return
     *     possible object is
     *     {@link IVLPQ }
     *     
     */
    public IVLPQ getDeliveryRate() {
        return deliveryRate;
    }

    /**
     * Sets the value of the deliveryRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLPQ }
     *     
     */
    public void setDeliveryRate(IVLPQ value) {
        this.deliveryRate = value;
    }

    /**
     * Gets the value of the dosingPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link IVLPQ }
     *     
     */
    public IVLPQ getDosingPeriod() {
        return dosingPeriod;
    }

    /**
     * Sets the value of the dosingPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLPQ }
     *     
     */
    public void setDosingPeriod(IVLPQ value) {
        this.dosingPeriod = value;
    }

    /**
     * Gets the value of the dosingPeriodIntervalIsImportant property.
     * 
     * @return
     *     possible object is
     *     {@link BL }
     *     
     */
    public BL getDosingPeriodIntervalIsImportant() {
        return dosingPeriodIntervalIsImportant;
    }

    /**
     * Sets the value of the dosingPeriodIntervalIsImportant property.
     * 
     * @param value
     *     allowed object is
     *     {@link BL }
     *     
     */
    public void setDosingPeriodIntervalIsImportant(BL value) {
        this.dosingPeriodIntervalIsImportant = value;
    }

    /**
     * Gets the value of the deliveryMethod property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getDeliveryMethod() {
        return deliveryMethod;
    }

    /**
     * Sets the value of the deliveryMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setDeliveryMethod(CD value) {
        this.deliveryMethod = value;
    }

    /**
     * Gets the value of the approachBodySite property.
     * 
     * @return
     *     possible object is
     *     {@link BodySite }
     *     
     */
    public BodySite getApproachBodySite() {
        return approachBodySite;
    }

    /**
     * Sets the value of the approachBodySite property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodySite }
     *     
     */
    public void setApproachBodySite(BodySite value) {
        this.approachBodySite = value;
    }

    /**
     * Gets the value of the targetBodySite property.
     * 
     * @return
     *     possible object is
     *     {@link BodySite }
     *     
     */
    public BodySite getTargetBodySite() {
        return targetBodySite;
    }

    /**
     * Sets the value of the targetBodySite property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodySite }
     *     
     */
    public void setTargetBodySite(BodySite value) {
        this.targetBodySite = value;
    }

}
