//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.01 at 06:23:30 PM CEST 
//


package org.opencds.vmr.v1_0.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * This is the Event of a pharmacy filling a prescription.
 * 
 * <p>Java class for SubstanceDispensationEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubstanceDispensationEvent">
 *   &lt;complexContent>
 *     &lt;extension base="{org.opencds.vmr.v1_0.schema.vmr}SubstanceAdministrationBase">
 *       &lt;sequence>
 *         &lt;element name="daysSupply" type="{org.opencds.vmr.v1_0.schema.datatypes}INT" minOccurs="0"/>
 *         &lt;element name="dispensationQuantity" type="{org.opencds.vmr.v1_0.schema.datatypes}PQ" minOccurs="0"/>
 *         &lt;element name="doseRestriction" type="{org.opencds.vmr.v1_0.schema.vmr}DoseRestriction" minOccurs="0"/>
 *         &lt;element name="dispensationTime" type="{org.opencds.vmr.v1_0.schema.datatypes}IVL_TS" minOccurs="0"/>
 *         &lt;element name="fillNumber" type="{org.opencds.vmr.v1_0.schema.datatypes}INT" minOccurs="0"/>
 *         &lt;element name="fillsRemaining" type="{org.opencds.vmr.v1_0.schema.datatypes}INT" minOccurs="0"/>
 *         &lt;element name="relatedEntity" type="{org.opencds.vmr.v1_0.schema.vmr}RelatedEntity" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="relatedClinicalStatement" type="{org.opencds.vmr.v1_0.schema.vmr}RelatedClinicalStatement" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubstanceDispensationEvent", propOrder = {
    "daysSupply",
    "dispensationQuantity",
    "doseRestriction",
    "dispensationTime",
    "fillNumber",
    "fillsRemaining",
    "relatedEntity",
    "relatedClinicalStatement"
})
public class SubstanceDispensationEvent
    extends SubstanceAdministrationBase
{

    protected INT daysSupply;
    protected PQ dispensationQuantity;
    protected DoseRestriction doseRestriction;
    protected IVLTS dispensationTime;
    protected INT fillNumber;
    protected INT fillsRemaining;
    protected List<RelatedEntity> relatedEntity;
    protected List<RelatedClinicalStatement> relatedClinicalStatement;

    /**
     * Gets the value of the daysSupply property.
     * 
     * @return
     *     possible object is
     *     {@link INT }
     *     
     */
    public INT getDaysSupply() {
        return daysSupply;
    }

    /**
     * Sets the value of the daysSupply property.
     * 
     * @param value
     *     allowed object is
     *     {@link INT }
     *     
     */
    public void setDaysSupply(INT value) {
        this.daysSupply = value;
    }

    /**
     * Gets the value of the dispensationQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link PQ }
     *     
     */
    public PQ getDispensationQuantity() {
        return dispensationQuantity;
    }

    /**
     * Sets the value of the dispensationQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link PQ }
     *     
     */
    public void setDispensationQuantity(PQ value) {
        this.dispensationQuantity = value;
    }

    /**
     * Gets the value of the doseRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link DoseRestriction }
     *     
     */
    public DoseRestriction getDoseRestriction() {
        return doseRestriction;
    }

    /**
     * Sets the value of the doseRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoseRestriction }
     *     
     */
    public void setDoseRestriction(DoseRestriction value) {
        this.doseRestriction = value;
    }

    /**
     * Gets the value of the dispensationTime property.
     * 
     * @return
     *     possible object is
     *     {@link IVLTS }
     *     
     */
    public IVLTS getDispensationTime() {
        return dispensationTime;
    }

    /**
     * Sets the value of the dispensationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLTS }
     *     
     */
    public void setDispensationTime(IVLTS value) {
        this.dispensationTime = value;
    }

    /**
     * Gets the value of the fillNumber property.
     * 
     * @return
     *     possible object is
     *     {@link INT }
     *     
     */
    public INT getFillNumber() {
        return fillNumber;
    }

    /**
     * Sets the value of the fillNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link INT }
     *     
     */
    public void setFillNumber(INT value) {
        this.fillNumber = value;
    }

    /**
     * Gets the value of the fillsRemaining property.
     * 
     * @return
     *     possible object is
     *     {@link INT }
     *     
     */
    public INT getFillsRemaining() {
        return fillsRemaining;
    }

    /**
     * Sets the value of the fillsRemaining property.
     * 
     * @param value
     *     allowed object is
     *     {@link INT }
     *     
     */
    public void setFillsRemaining(INT value) {
        this.fillsRemaining = value;
    }

    /**
     * Gets the value of the relatedEntity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedEntity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedEntity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedEntity }
     * 
     * 
     */
    public List<RelatedEntity> getRelatedEntity() {
        if (relatedEntity == null) {
            relatedEntity = new ArrayList<RelatedEntity>();
        }
        return this.relatedEntity;
    }

    /**
     * Gets the value of the relatedClinicalStatement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedClinicalStatement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedClinicalStatement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedClinicalStatement }
     * 
     * 
     */
    public List<RelatedClinicalStatement> getRelatedClinicalStatement() {
        if (relatedClinicalStatement == null) {
            relatedClinicalStatement = new ArrayList<RelatedClinicalStatement>();
        }
        return this.relatedClinicalStatement;
    }

}
