//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.01 at 08:58:27 PM CEST 
//


package org.opencds.vmr.v1_0.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A virtual medical record (vMR) contains data about a patient relevant for CDS, either with regard to the data used for generating inferences (input) or the conclusions reached as a result of analyzing the data (output).  A vMR may contain, for example, problems and medications or CDS-generated assessments and recommended actions.  Note that CDS-generated assessments and recommended actions would typically be considered a CDS output but could also be used as a CDS input as well (e.g., prior CDS system recommendations could influence current CDS system recommendations).
 * 
 * This model does allow for the presence of data belonging to related persons (such as in the case of family history, or public health infectious disease cases) for a single patient.  These related persons are modeled as EvaluatedPersons who have associated ClinicalStatements.  Note that this model is not designed to be a data model for providing CDS for a large population.
 * 
 * Note that enumerations and value domains are anticipated to be specified in profiles in additional ballots.
 * 
 * <p>Java class for VMR complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VMR">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="templateId" type="{org.opencds.vmr.v1_0.schema.datatypes}II" maxOccurs="unbounded"/>
 *         &lt;element name="patient" type="{org.opencds.vmr.v1_0.schema.vmr}EvaluatedPerson"/>
 *         &lt;element name="otherEvaluatedPersons" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="evaluatedPerson" type="{org.opencds.vmr.v1_0.schema.vmr}EvaluatedPerson" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="evaluatedPersonRelationships" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="evaluatedPersonRelationship" type="{org.opencds.vmr.v1_0.schema.vmr}EntityRelationship" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VMR", propOrder = {
    "templateId",
    "patient",
    "otherEvaluatedPersons",
    "evaluatedPersonRelationships"
})
public class VMR {

    @XmlElement(required = true)
    protected List<II> templateId;
    @XmlElement(required = true)
    protected EvaluatedPerson patient;
    protected VMR.OtherEvaluatedPersons otherEvaluatedPersons;
    protected VMR.EvaluatedPersonRelationships evaluatedPersonRelationships;

    /**
     * Gets the value of the templateId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the templateId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getTemplateId() {
        if (templateId == null) {
            templateId = new ArrayList<II>();
        }
        return this.templateId;
    }

    /**
     * Gets the value of the patient property.
     * 
     * @return
     *     possible object is
     *     {@link EvaluatedPerson }
     *     
     */
    public EvaluatedPerson getPatient() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     * 
     * @param value
     *     allowed object is
     *     {@link EvaluatedPerson }
     *     
     */
    public void setPatient(EvaluatedPerson value) {
        this.patient = value;
    }

    /**
     * Gets the value of the otherEvaluatedPersons property.
     * 
     * @return
     *     possible object is
     *     {@link VMR.OtherEvaluatedPersons }
     *     
     */
    public VMR.OtherEvaluatedPersons getOtherEvaluatedPersons() {
        return otherEvaluatedPersons;
    }

    /**
     * Sets the value of the otherEvaluatedPersons property.
     * 
     * @param value
     *     allowed object is
     *     {@link VMR.OtherEvaluatedPersons }
     *     
     */
    public void setOtherEvaluatedPersons(VMR.OtherEvaluatedPersons value) {
        this.otherEvaluatedPersons = value;
    }

    /**
     * Gets the value of the evaluatedPersonRelationships property.
     * 
     * @return
     *     possible object is
     *     {@link VMR.EvaluatedPersonRelationships }
     *     
     */
    public VMR.EvaluatedPersonRelationships getEvaluatedPersonRelationships() {
        return evaluatedPersonRelationships;
    }

    /**
     * Sets the value of the evaluatedPersonRelationships property.
     * 
     * @param value
     *     allowed object is
     *     {@link VMR.EvaluatedPersonRelationships }
     *     
     */
    public void setEvaluatedPersonRelationships(VMR.EvaluatedPersonRelationships value) {
        this.evaluatedPersonRelationships = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="evaluatedPersonRelationship" type="{org.opencds.vmr.v1_0.schema.vmr}EntityRelationship" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "evaluatedPersonRelationship"
    })
    public static class EvaluatedPersonRelationships {

        @XmlElement(required = true)
        protected List<EntityRelationship> evaluatedPersonRelationship;

        /**
         * Gets the value of the evaluatedPersonRelationship property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the evaluatedPersonRelationship property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEvaluatedPersonRelationship().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EntityRelationship }
         * 
         * 
         */
        public List<EntityRelationship> getEvaluatedPersonRelationship() {
            if (evaluatedPersonRelationship == null) {
                evaluatedPersonRelationship = new ArrayList<EntityRelationship>();
            }
            return this.evaluatedPersonRelationship;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="evaluatedPerson" type="{org.opencds.vmr.v1_0.schema.vmr}EvaluatedPerson" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "evaluatedPerson"
    })
    public static class OtherEvaluatedPersons {

        @XmlElement(required = true)
        protected List<EvaluatedPerson> evaluatedPerson;

        /**
         * Gets the value of the evaluatedPerson property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the evaluatedPerson property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEvaluatedPerson().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EvaluatedPerson }
         * 
         * 
         */
        public List<EvaluatedPerson> getEvaluatedPerson() {
            if (evaluatedPerson == null) {
                evaluatedPerson = new ArrayList<EvaluatedPerson>();
            }
            return this.evaluatedPerson;
        }

    }

}
