package TFG_v1

import org.opencds.vmr.v1_0.internal.*;
import org.opencds.vmr.v1_0.internal.datatypes.*;
import javax.swing.JDialog;
import javax.swing.JOptionPane;


global java.util.Date evalTime
global String clientLanguage
global String clientTimeZoneOffset
global String focalPersonId
global java.util.HashSet assertions
global java.util.HashMap namedObjects

// PRUEBAS
rule "reglaDePrueba"
	no-loop
	when
		// existe una persona
  		//$person : EvaluatedPerson()
  		// tiene un observation result asociado a esa persona
  		//$or : ObservationResult(evaluatedPersonId == $person.id)
  		// obtenemos el objeto que tiene dentro el valor de CPIS
  		//$cpis : ObservationResult(evaluatedPersonId == $person.id && observationFocus.getCode()=="CPIS")
  		// el observation result es del tipo temperatura y que la temperatura sea > 38.9 o <= 36.4
  		//eval($or.getObservationFocus().getCode()=="temp_corp")
  		$p : ClinicalStatementRelationship()
	then
		//$or.setToBeReturned(true);
		//System.out.println($or.getObservationFocus().getCode());
		//System.out.println("OERKOERKOR");
		System.out.println($p.getId());
				System.out.println($p.getSourceId());
		
				System.out.println($p.getTargetId());
		
		//System.out.println($p);
end

rule "reglaDePrueba2"
	no-loop
	when
		// existe una persona
  		$person : EvaluatedPerson()
  		// tiene un observation result asociado a esa persona
  		$or : ObservationResult(evaluatedPersonId == $person.id)
  		// obtenemos el objeto que tiene dentro el valor de CPIS
  		//$cpis : ObservationResult(evaluatedPersonId == $person.id && observationFocus.getCode()=="CPIS")
  		// el observation result es del tipo temperatura y que la temperatura sea > 38.9 o <= 36.4
  		//eval($or.getObservationFocus().getCode()=="temp_corp")
  		//$p : ClinicalStatementRelationship()
	then
		//$or.setToBeReturned(true);
		//System.out.println($or.getObservationFocus().getCode());
		System.out.println($or.getId());
		//System.out.println("OERKOERKOR");
		//System.out.println($p.getId());
			//	System.out.println($p.getSourceId());
		
		//		System.out.println($p.getTargetId());
		
		//System.out.println($p);
end
	

