package TFG_v1

// atributos globales que usa el estandar 
global java.util.Date evalTime
global String clientLanguage
global String clientTimeZoneOffset
global String focalPersonId
global java.util.HashSet assertions
global java.util.HashMap namedObjects

import org.opencds.cliente.modelo.Paciente;

// rules dialect
dialect "mvel"

// declare the CPIScore as a time driven event so that we can implement temporal rules
declare CPIScore
   @role(event) 
end

// CPIS RULES

rule "CPISHighTemperature"

// *********** END OF AUDIT METADATA INFO ************************ 
	lock-on-active
    salience 100 
    no-loop
    agenda-group "cpis"
    when
        $paciente: Paciente (temperature > 36.5 && temperature <= 38.4)
    then
        modify ($patient) {CPIS +=0};
        //$patient.CPIS += 0;
        //update( $patient );
        System.out.println( "CPIS NOT changed :High Temp, CPI of patient " + $patient.name + " increased by 0, final value = " + $patient.CPIS);
end 