[then] Output.Nested.Obs.Focus.CDValue.Assrt - Create nested observation with ID {nestedIdValue} within enclosing observation ID {ROOT} focused on {focus:ENUM:ObservationFocusConcept.openCdsConceptCode} coded value {CDValue:ENUM:ObservationCodedValueConcept.openCdsConceptCode} = 
IVLDate obsTime{nestedIdValue}{ROOT}{CDValue} = new IVLDate(); 
obsTime{nestedIdValue}{ROOT}{CDValue}.setLow($evalTime); 
obsTime{nestedIdValue}{ROOT}{CDValue}.setHigh($evalTime); 
ObservationResult childObs{nestedIdValue}{ROOT}{CDValue} = new ObservationResult(); 
String childObs{nestedIdValue}{ROOT}{CDValue}Id = "2.16.840.1.113883.3.795.10.1^{nestedIdValue}"; 
childObs{nestedIdValue}{ROOT}{CDValue}.setId(childObs{nestedIdValue}{ROOT}{CDValue}Id); 
childObs{nestedIdValue}{ROOT}{CDValue}.setEvaluatedPersonId($evaluatedPersonId); 
childObs{nestedIdValue}{ROOT}{CDValue}.setObservationEventTime(obsTime{nestedIdValue}{ROOT}{CDValue}); 
childObs{nestedIdValue}{ROOT}{CDValue}.setSubjectIsFocalPerson($evaluatedPersonId == $focalPersonId); 
CD childObs{nestedIdValue}{ROOT}{CDValue}Focus = new CD(); 
childObs{nestedIdValue}{ROOT}{CDValue}Focus.setCodeSystem("2.16.840.1.113883.3.795.12.1.1"); 
childObs{nestedIdValue}{ROOT}{CDValue}Focus.setCodeSystemName("OpenCDS concepts"); 
childObs{nestedIdValue}{ROOT}{CDValue}Focus.setCode("{focus}"); 
childObs{nestedIdValue}{ROOT}{CDValue}Focus.setDisplayName(GetOpenCDSConceptName("{focus}")); 
childObs{nestedIdValue}{ROOT}{CDValue}.setObservationFocus(childObs{nestedIdValue}{ROOT}{CDValue}Focus); 
CD childObs{nestedIdValue}{ROOT}{CDValue}ConceptValue = new CD(); 
childObs{nestedIdValue}{ROOT}{CDValue}ConceptValue.setCodeSystem("2.16.840.1.113883.3.795.12.1.1"); 
childObs{nestedIdValue}{ROOT}{CDValue}ConceptValue.setCodeSystemName("OpenCDS concepts"); 
childObs{nestedIdValue}{ROOT}{CDValue}ConceptValue.setCode("{CDValue}"); 
childObs{nestedIdValue}{ROOT}{CDValue}ConceptValue.setDisplayName(GetOpenCDSConceptName("{CDValue}")); 
ObservationValue childObs{nestedIdValue}{ROOT}{CDValue}Value = new ObservationValue(); 
childObs{nestedIdValue}{ROOT}{CDValue}Value.setConcept(childObs{nestedIdValue}{ROOT}{CDValue}ConceptValue); 
childObs{nestedIdValue}{ROOT}{CDValue}.setObservationValue(childObs{nestedIdValue}{ROOT}{CDValue}Value); 
childObs{nestedIdValue}{ROOT}{CDValue}.setClinicalStatementToBeRoot(false); 
childObs{nestedIdValue}{ROOT}{CDValue}.setToBeReturned(true); 
ClinicalStatementRelationship rel{nestedIdValue}{ROOT}{CDValue} = new ClinicalStatementRelationship(); 
rel{nestedIdValue}{ROOT}{CDValue}.setSourceId("2.16.840.1.113883.3.795.10.1^{ROOT}"); 
rel{nestedIdValue}{ROOT}{CDValue}.setTargetId("2.16.840.1.113883.3.795.10.1^{nestedIdValue}"); 
CD rel{nestedIdValue}{ROOT}{CDValue}Code = new CD(); 
rel{nestedIdValue}{ROOT}{CDValue}Code.setCodeSystem("2.16.840.1.113883.3.795.12.1.1"); 
rel{nestedIdValue}{ROOT}{CDValue}Code.setCodeSystemName("OpenCDS concepts"); 
rel{nestedIdValue}{ROOT}{CDValue}Code.setCode("C67"); 
rel{nestedIdValue}{ROOT}{CDValue}Code.setDisplayName("Is contained by"); 
rel{nestedIdValue}{ROOT}{CDValue}.setTargetRelationshipToSource(rel{nestedIdValue}{ROOT}{CDValue}Code); 
java.util.List<RelationshipToSource> childObs{nestedIdValue}{ROOT}{CDValue}RelationshipToSources = new java.util.ArrayList<RelationshipToSource>(); 
RelationshipToSource childObs{nestedIdValue}{ROOT}{CDValue}RelationshipToSource = new RelationshipToSource(); 
childObs{nestedIdValue}{ROOT}{CDValue}RelationshipToSource.setSourceId("2.16.840.1.113883.3.795.10.1^{ROOT}"); 
childObs{nestedIdValue}{ROOT}{CDValue}RelationshipToSource.setRelationshipToSource(rel{nestedIdValue}{ROOT}{CDValue}Code); 
childObs{nestedIdValue}{ROOT}{CDValue}RelationshipToSources.add(childObs{nestedIdValue}{ROOT}{CDValue}RelationshipToSource); 
insert(childObs{nestedIdValue}{ROOT}{CDValue}); 
namedObjects.put("childObs{nestedIdValue}{ROOT}{CDValue}", childObs{nestedIdValue}{ROOT}{CDValue}); 
insert(rel{nestedIdValue}{ROOT}{CDValue}); 
namedObjects.put("rel{nestedIdValue}{ROOT}{CDValue}", rel{nestedIdValue}{ROOT}{CDValue}); //OutputNestedObservationFocusValueFromAssertDsl|||nestedIdValue=={nestedIdValue}|||ROOT=={ROOT}|||focus=={focus}|||CDValue=={CDValue}