[then] Output.Nested.Assert.All - Create nested observation with ID {nestedIdValue} within enclosing observation ID {ROOT} containing a list of all assertions in working memory = 
IVLDate obsTime{nestedIdValue}{ROOT} = new IVLDate(); 
obsTime{nestedIdValue}{ROOT}.setLow($evalTime); 
obsTime{nestedIdValue}{ROOT}.setHigh($evalTime); 
ObservationResult childObs{nestedIdValue}{ROOT} = new ObservationResult(); 
String childObs{nestedIdValue}{ROOT}Id = "2.16.840.1.113883.3.795.10.1^{nestedIdValue}"; 
childObs{nestedIdValue}{ROOT}.setId(childObs{nestedIdValue}{ROOT}Id); 
childObs{nestedIdValue}{ROOT}.setEvaluatedPersonId($evaluatedPersonId); 
childObs{nestedIdValue}{ROOT}.setObservationEventTime(obsTime{nestedIdValue}{ROOT}); 
childObs{nestedIdValue}{ROOT}.setSubjectIsFocalPerson($evaluatedPersonId == $focalPersonId); 
CD childObs{nestedIdValue}{ROOT}Focus = new CD(); 
childObs{nestedIdValue}{ROOT}Focus.setCodeSystem("2.16.840.1.113883.3.795.12.1.1"); 
childObs{nestedIdValue}{ROOT}Focus.setCodeSystemName("OpenCDS concepts"); 
childObs{nestedIdValue}{ROOT}Focus.setCode("assertions"); 
childObs{nestedIdValue}{ROOT}Focus.setDisplayName("Assertions found in working memory"); 
childObs{nestedIdValue}{ROOT}.setObservationFocus(childObs{nestedIdValue}{ROOT}Focus); 
childObs{nestedIdValue}{ROOT}.setClinicalStatementToBeRoot(false); 
childObs{nestedIdValue}{ROOT}.setToBeReturned(true); 
ObservationValue obsValue{nestedIdValue}{ROOT} = new ObservationValue();
obsValue{nestedIdValue}{ROOT}.setText(assertions.toString());
childObs{nestedIdValue}{ROOT}.setObservationValue(obsValue{nestedIdValue}{ROOT}); 
ClinicalStatementRelationship rel{nestedIdValue}{ROOT} = new ClinicalStatementRelationship(); 
rel{nestedIdValue}{ROOT}.setSourceId("2.16.840.1.113883.3.795.10.1^{ROOT}"); 
rel{nestedIdValue}{ROOT}.setTargetId("2.16.840.1.113883.3.795.10.1^{nestedIdValue}"); 
CD rel{nestedIdValue}{ROOT}Code = new CD(); 
rel{nestedIdValue}{ROOT}Code.setCodeSystem("2.16.840.1.113883.3.795.12.1.1"); 
rel{nestedIdValue}{ROOT}Code.setCodeSystemName("OpenCDS concepts"); 
rel{nestedIdValue}{ROOT}Code.setCode("C67"); 
rel{nestedIdValue}{ROOT}Code.setDisplayName("Is contained by"); 
rel{nestedIdValue}{ROOT}.setTargetRelationshipToSource(rel{nestedIdValue}{ROOT}Code); 
java.util.List<RelationshipToSource> childObs{nestedIdValue}{ROOT}RelationshipToSources = new java.util.ArrayList<RelationshipToSource>(); 
RelationshipToSource childObs{nestedIdValue}{ROOT}RelationshipToSource = new RelationshipToSource(); 
childObs{nestedIdValue}{ROOT}RelationshipToSource.setSourceId("2.16.840.1.113883.3.795.10.1^{ROOT}"); 
childObs{nestedIdValue}{ROOT}RelationshipToSource.setRelationshipToSource(rel{nestedIdValue}{ROOT}Code); 
childObs{nestedIdValue}{ROOT}RelationshipToSources.add(childObs{nestedIdValue}{ROOT}RelationshipToSource); 
insert(childObs{nestedIdValue}{ROOT}); 
namedObjects.put("childObs{nestedIdValue}{ROOT}", childObs{nestedIdValue}{ROOT}); 
insert(rel{nestedIdValue}{ROOT}); 
namedObjects.put("rel{nestedIdValue}{ROOT}", rel{nestedIdValue}{ROOT}); //OutputNestedObservationAssertionsAllDsl|||nestedIdValue=={nestedIdValue}|||ROOT=={ROOT}
